app/models.py
from app import db
from datetime import datetime
from flask_wtf.file import FileField, FileRequired

class Tenant(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    property_name = db.Column(db.String(64))
    property_add_01 = db.Column(db.String(128))
    property_add_02 = db.Column(db.String(128))
    property_add_03 = db.Column(db.String(128))
    property_add_04 = db.Column(db.String(128))
    unit_name = db.Column(db.String(64))
    tenant_name = db.Column(db.String(64))
    lease_start_date = db.Column(db.DateTime)
    lease_end_date = db.Column(db.DateTime)
    lease_years = db.Column(db.Integer)
    current_rent = db.Column(db.Numeric)
    creation_time = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return '<Tenant {} with id: {}, property_name: {}, prop_add_01: {}, ' \
               'prop_add_02: {}, prop_add_03: {}, prop_add_04:{}>' \
               'unit_name: {}, tenant_name: {}, lease_start_date:{}>' \
               'lease_end_date: {}, lease_years: {}, current_rent:{}>' \
               'creation_time: {}' \
            .format(self.id, self.property_name, self.property_add_01,
                    self.property_add_02, self.property_add_03, self.property_add_04,
                    self.unit_name, self.tenant_name, self.lease_start_date,
                    self.lease_end_date, self.lease_years, self.current_rent,
                    self.creation_time)

app/__init__.py
import logging
from logging.handlers import RotatingFileHandler
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import config
from flask_bootstrap import Bootstrap

db = SQLAlchemy()
migrate = Migrate()
bootstrap = Bootstrap()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    migrate.init_app(app, db)
    bootstrap.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    if not app.debug and not app.testing:
        if app.config['LOG_TO_STDOUT']:
            stream_handler = logging.StreamHandler()
            stream_handler.setLevel(logging.DEBUG)
            app.logger.addHandler(stream_handler)
        else:

            if not os.path.exists('logs'):
                os.mkdir('logs')
            file_handler = RotatingFileHandler('logs/mast_manager.log',
                                               maxBytes=10240, backupCount=10)
            file_handler.setFormatter(logging.Formatter(
                '%(asctime)s %(levelname)s: %(message)s '
                '[in %(pathname)s:%(lineno)d]'))
            file_handler.setLevel(logging.INFO)
            app.logger.addHandler(file_handler)

            app.logger.setLevel(logging.INFO)
            app.logger.info('Mast Manager startup')


    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import views, errors, data_ingestion

app/main/views.py
import os
from app.models import Tenant
from app.main import bp
from flask import render_template,request, url_for,current_app,flash, redirect
from werkzeug.utils import secure_filename
from .data_ingestion import loadTenants, cleanTenants
from collections import Counter
from datetime import datetime


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
    page = request.args.get('page', 1, type=int)
    tenants = Tenant.query.order_by(Tenant.current_rent.asc())\
        .paginate(page, current_app.config['TENANT_PER_PAGE'], False)

    next_url = url_for('main.index', page=tenants.next_num) \
        if tenants.has_next else None
    prev_url = url_for('main.index', page=tenants.prev_num) \
        if tenants.has_prev else None

    return render_template('index.html', tenants=tenants.items,
                           next_url=next_url, prev_url=prev_url,
                           page=page, per_page=current_app.config['TENANT_PER_PAGE'])

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in current_app.config['ALLOWED_EXTENSIONS']

@bp.route('/upload_file', methods=['GET', 'POST'])
def upload_file():

    current_app.logger.debug("uploading file section")

    if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        # if user does not select file, browser also
        # submit an empty part without filename
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)

        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            current_app.logger.debug("file name is {}".format(filename))

            file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
            flash('File successfully uploaded')
            loadTenants(filename)
            flash('Tenants successfully loaded')
            return redirect(url_for('main.index'))
        else:
            flash('Allowed file type is csv')
            return redirect(request.url)

    return render_template('upload.html')

@bp.route('/clean_tenants', methods=['GET', 'POST'])
def clean_tenants():
    cleanTenants()
    flash('Tenants successfully removed')
    return render_template('index.html')

@bp.route('/menu', methods=['GET', 'POST'])
def menu():
    return render_template('menu.html',title='Menu')

@bp.route('/list_tenants/<limit>', methods=['GET', 'POST'])
def list_tenants(limit):

    tenants = Tenant.query.order_by(Tenant.current_rent.asc()).limit(limit).all()

    flash('5 tenants listed ascending order by current rent')
    return render_template('index.html', tenants=tenants)


@bp.route('/list_lease_years/<year>', methods=['GET', 'POST'])
def list_lease_years(year):
    page = request.args.get('page', 1, type=int)
    tenants = Tenant.query.order_by(Tenant.current_rent.asc()).\
        filter_by(lease_years = 25).\
        paginate(page, current_app.config['TENANT_PER_PAGE'], False)

    tenant_current_rent_list = [tenant.current_rent for tenant in tenants.items]
    total = sum (tenant_current_rent_list)
    flash('Tenants within 25 years listed and their rent summed up via comprehensions')

    next_url = url_for('main.index', page=tenants.next_num) \
        if tenants.has_next else None
    prev_url = url_for('main.index', page=tenants.prev_num) \
        if tenants.has_prev else None

    return render_template('index.html', tenants=tenants.items,next_url=next_url, prev_url=prev_url,
                           total=total, page=page, per_page=current_app.config['TENANT_PER_PAGE'])

@bp.route('/group_by_name', methods=['GET', 'POST'])
def group_by_name():
    tenants = Tenant.query.order_by(Tenant.current_rent.asc()).all()

    tenant_names = [tenant.tenant_name for tenant in tenants]
    tenant_dict = dict(Counter(tenant_names))
    sorted_names = {k: v for k, v in sorted(tenant_dict.items(), key=lambda item: item[1],reverse=True)}

    flash('Tenants grouped by their names and sorted by their number of counts in descending order')

    return render_template('group_by_name.html', names=sorted_names)

@bp.route('/list_between_start_date', methods=['GET', 'POST'])
def list_between_start_date():
    page = request.args.get('page', 1, type=int)
    tenants = Tenant.query.order_by(Tenant.current_rent.asc()). \
        filter(Tenant.lease_start_date.
               between(datetime(1999, 6, 1),
                       datetime(2007, 8, 31)))\
        .paginate(page, current_app.config['TENANT_PER_PAGE'], False)

    next_url = url_for('main.index', page=tenants.next_num) \
        if tenants.has_next else None
    prev_url = url_for('main.index', page=tenants.prev_num) \
        if tenants.has_prev else None

    flash('Lease start date between 1st Jun 1999 and 31st Aug 2007')
    return render_template('index.html', tenants=tenants.items,next_url=next_url, prev_url=prev_url,
                           page=page, per_page=current_app.config['TENANT_PER_PAGE'])

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Mast Manager</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">{{'Home' }}</a></li>

                    <li><a href="{{ url_for('main.upload_file') }}">{{'Upload' }}</a></li>

                    <li><a href="{{ url_for('main.clean_tenants') }}">{{'Clean up' }}</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">

                    <li><a href="{{ url_for('main.menu') }}">{{ 'Menu' }}</a></li>

                </ul>
            </div>

        </div>
    </nav>
{% endblock %}



{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/group_by_name.html
{% extends "base.html" %}

{% block app_content %}

<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Tenant Name</th>
      <th scope="col">Count</th>

    </tr>
  </thead>
  <tbody>

    {% for key, value in names.items() %}
    <tr>
      <th scope="row">{{loop.index}}</th>
      <td>{{key}}</td>
      <td>{{value}}</td>

    </tr>
   {% endfor %}
  </tbody>
</table>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block app_content %}
 <table class="table table-hover">
     <thead>
          <tr>
              {% if page and per_page%}
              <th scope="col">#</th>
               {% else %}
               {% endif %}
              <th>property_name</th>
              <th>add_01</th>
              <th>add_02</th>
              <th>add_03</th>
              <th>add_04</th>
              <th>unit_name</th>
              <th>tenant_name</th>
              <th>lease_start</th>
              <th>lease_end</th>
              <th>lease_years</th>
              <th>current_rent</th>

          </tr>
     </thead>
     <tbody>
    {% for tenant in tenants %}
           <tr>
               {% if page and per_page%}
                    <th scope="row">{{ loop.index + (page - 1) * per_page }}</th>
                {% else %}

               {% endif %}

               <td>{{ tenant.property_name }}</td>
               <td>{{ tenant.property_add_01 }}</td>
               <td>{{ tenant.property_add_02 }}</td>
               <td>{{ tenant.property_add_03 }}</td>
               <td>{{ tenant.property_add_04 }}</td>
               <td>{{ tenant.unit_name }}</td>
               <td>{{ tenant.tenant_name }}</td>
               <td>{{ tenant.lease_start_date.strftime('%d/%m/%Y') }}</td>
               <td>{{ tenant.lease_end_date.strftime('%d/%m/%Y') }}</td>
               <td>{{ tenant.lease_years }}</td>
               <td>{{ "{:.2f}".format(tenant.current_rent) }}</td>
           </tr>
    {% endfor %}
    <div>
     <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> {{ 'Previous tenants' }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ 'Next tenants' }} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
    </div>

     </tbody>
      </table>
<div>
     {% if total %}<td colspan="11"><p class="text-right">Total: {{ "{:.2f}".format(total) }}</p></td>
        {% else %}{% endif %}
    </div>
{% endblock %}

app/templates/menu.html
{% extends "base.html" %}

{% block app_content %}

<div class="list-group">
  <a href="{{ url_for('main.list_tenants', limit=5) }}" class="list-group-item list-group-item-action">
    1) Obtain the first 5 items from the list in ascending order
  </a>
    <a href="{{ url_for('main.list_lease_years', year=25) }}" class="list-group-item list-group-item-action">
    2) List tenants within 'Lease year = 25'
  </a>
    <a href="{{ url_for('main.group_by_name') }}" class="list-group-item list-group-item-action">
    3) Group by number of the mast count
  </a>
    <a href="{{ url_for('main.list_between_start_date') }}" class="list-group-item list-group-item-action">
    4) List the data with Lease Start Date between 1st June 1999 and 31 August 2007
  </a>
</div>
{% endblock %}

app/templates/upload.html
{% extends "base.html" %}

{% block app_content %}
<h1>Upload new File</h1>
    <form method=post enctype=multipart/form-data>
      <input type="file" name="file" autocomplete="off" required>
      <input type=submit value=Upload>
    </form>
{% endblock %}